In [1]:
import numpy as np

In [2]:
array_1d=np.array([-1,2,0,12,-1,21,23,-12,12])

In [3]:
np.array([-1,2,0,12,-1,21,23,-12,12])[0]

-1

In [4]:
np.array([-1,2,0,12,-1,21,23,-12,12])[0:3]

array([-1,  2,  0])

In [5]:
np.array([-1,2,0,12,-1,21,23,-12,12])[-2]

-12

In [6]:
np.array([-1,2,0,12,-1,21,23,-12,12])[1:-2]

array([ 2,  0, 12, -1, 21, 23])

In [7]:
array_1d[:2]

array([-1,  2])

In [8]:
array_1d[3:]

array([ 12,  -1,  21,  23, -12,  12])

In [9]:
arun=np.arange(24)
arun.shape=(6,4)
arun

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
arun[2]

array([ 8,  9, 10, 11])

In [11]:
arun[-3]

array([12, 13, 14, 15])

In [12]:
arun[4,3]

19

In [13]:
r=2
c=2
arun[r,c]

10

In [14]:
arun[c,r]

10

In [15]:
arun[2:4,2:3]

array([[10],
       [14]])

In [16]:
arun[2:4,2:4]

array([[10, 11],
       [14, 15]])

In [17]:
array_1d=np.arange(0,10)
#creating a 1d array

In [18]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
array_1d[0:5]=500


In [20]:
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [21]:
array_2d=np.ones((4,4))

In [22]:
array_2d[0]=300

In [23]:
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [24]:
#lets create a simpolke 1d array and brodcast to 2D_array
array_2d+[0,1,2,3]

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [25]:
array_2d+300
#array_2d + [300,2] , did it works? if not why?

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [44]:
array_1=np.arange(1,4)
array_2=np.arange(0,4)[:,np.newaxis]
#newaxis converts rows into coloumns
array_2

array([[0],
       [1],
       [2],
       [3]])

In [27]:
print(array_1)

print("Shape of array is : {},this is {}-D array"\
     .format(array_1.shape,len(array_1.shape)))

[0 1 2 3]
Shape of array is : (4,),this is 1-D array


In [28]:
print(array_2)

print("Shape of array is : {},this is {}-D array"\
     .format(array_2.shape,len(array_2.shape)))

[[0]
 [1]
 [2]
 [3]]
Shape of array is : (4, 1),this is 2-D array


In [29]:
array_1+array_2

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [30]:
array_2d=np.zeros((5,5)) #create zero matrix of size 5X5

In [31]:
array_2d.shape[1] # => (5,)
#shape of the first row
for i in range(array_2d.shape[1]): #takes just int 5 as range argumentarr
    array_2d[i]=i
array_2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [32]:
array_2d[[1,2,3]] #returns the rows of purticular indexs

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [33]:
array_2d[[3,0,4]] #returns the rows of purticular indexs in any order 

array([[3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [4., 4., 4., 4., 4.]])

In [34]:
#lets try another matrix
array_2d=np.arange(24)
array_2d.shape=(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
#grabing rows
array_2d[[2,4]]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [36]:
#grabing cloumns
array_2d[:,[3,2]]

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22]])

In [37]:
#lets simply create array using arange
array_1d=np.arange(10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
#lets create a bollean_array for a purticular condition

boll_array=array_2d>3
print(boll_array)
print("\n line break \n")
boll_array=array_1d>3
boll_array

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

 line break 



array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
# a number is even or not , boll_array
mod_2_mask_1d=0 == array_1d % 2
mod_2_mask_1d

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [40]:
#boolean masking with data

even_values=array_1d[mod_2_mask_1d] #returns value when its true
type(even_values) #masking is similar to mapping
even_values


array([0, 2, 4, 6, 8])

In [41]:
#lets do the same with 2d array
array_2d=np.arange(24)
array_2d.shape=(6,4)
print(array_2d)
mask_mod_2d=0==array_2d %2
print(mask_mod_2d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [42]:
array_2d[mask_mod_2d]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [43]:
print(array_2d[mask_mod_2d])

[ 0  2  4  6  8 10 12 14 16 18 20 22]
