In [99]:
import numpy as np

In [100]:
array_1d=np.array([-1,2,0,12,-1,21,23,-12,12])

In [101]:
np.array([-1,2,0,12,-1,21,23,-12,12])[0]

-1

In [102]:
np.array([-1,2,0,12,-1,21,23,-12,12])[0:3]

array([-1,  2,  0])

In [103]:
np.array([-1,2,0,12,-1,21,23,-12,12])[-2]

-12

In [104]:
np.array([-1,2,0,12,-1,21,23,-12,12])[1:-2]

array([ 2,  0, 12, -1, 21, 23])

In [105]:
array_1d[:2]

array([-1,  2])

In [106]:
array_1d[3:]

array([ 12,  -1,  21,  23, -12,  12])

In [107]:
arun=np.arange(24)
arun.shape=(6,4)
arun

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [108]:
arun[2]

array([ 8,  9, 10, 11])

In [109]:
arun[-3]

array([12, 13, 14, 15])

In [110]:
arun[4,3]

19

In [111]:
r=2
c=2
arun[r,c]

10

In [112]:
arun[c,r]

10

In [113]:
arun[2:4,2:3]

array([[10],
       [14]])

In [114]:
arun[2:4,2:4]

array([[10, 11],
       [14, 15]])