In [64]:
import numpy as np

In [65]:
arr=np.arange(5)

In [66]:
arr+arr

array([0, 2, 4, 6, 8])

In [67]:
arr-arr

array([0, 0, 0, 0, 0])

In [68]:
arr*arr

array([ 0,  1,  4,  9, 16])

In [69]:
#warning
arr/arr
#0/0 is replaced with nan

/var/folders/3h/67cz_t1j59q2lmg5hh9pfzq40000gn/T/ipykernel_10091/2455255115.py:2: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.])

In [70]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [71]:
# min and max
np.min(arr),np.max(arr)

(0, 4)

In [72]:
#trignometric funtions eg: sin,cos,tan
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [73]:
#calculate the exponential (e ^ ) of all the elements in arrau
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [74]:
#logarithemic to base e
np.log(arr)

/var/folders/3h/67cz_t1j59q2lmg5hh9pfzq40000gn/T/ipykernel_10091/2807864637.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [75]:
#covert angles form radian to degree 
np.deg2rad(arr)


array([0., 1., 2., 3., 4.])

In [76]:
#convert angles from degree to radian

np.rad2deg(np.deg2rad(arr))

array([0., 1., 2., 3., 4.])