In [145]:
import numpy as np

In [146]:
my_list = [-1,0,1]
my_list, type(my_list)

([-1, 0, 1], list)

In [147]:
my_array = np.array(my_list)
my_array,type(my_array)


(array([-1,  0,  1]), numpy.ndarray)

In [148]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [149]:
ar1=np.array(my_matrix)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
my_tuple = (-1,0,1)
my_array = np.array(my_tuple)
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [151]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [153]:
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

In [154]:
np.arange(0,10,2, dtype=int)

array([0, 2, 4, 6, 8])

In [155]:
np.linspace(1,15,15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [156]:
np.linspace(5,15,9, retstep=True)

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [157]:
my_space=np.linspace(5,15,9, retstep=True)
my_space

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [158]:
np.zeros(3)

array([0., 0., 0.])

In [159]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [160]:
np.ones(3)

array([1., 1., 1.])

In [161]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [162]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [163]:
np.random.rand(3)

array([0.39403556, 0.82108922, 0.32149574])

In [164]:
np.random.rand(3,5)

array([[0.41413273, 0.36128751, 0.50175361, 0.16000247, 0.84445681],
       [0.19634195, 0.29826767, 0.3513425 , 0.03419882, 0.31075032],
       [0.62762191, 0.53460724, 0.41862746, 0.20787469, 0.09649803]])

In [165]:
np.random.randn(2)

array([-0.99422335, -1.59778458])

In [166]:
np.random.randn(4,4)

array([[-0.67660602, -0.38042773,  1.37629894,  0.59684444],
       [-0.56197031,  0.36029109, -0.281351  , -0.92367146],
       [ 0.46343581, -0.30959195, -0.18973136, -0.77376695],
       [-0.15791539, -0.247322  , -0.47076874, -0.21883977]])

In [167]:
np.random.randint(1,100)

33

In [168]:
np.random.randint(1,100,10)

array([78, 50, 55, 33, 99, 65, 35, 98, 21, 15])

In [169]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [170]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [171]:
np.random.randint(1,100,10).max()

91

In [172]:
np.random.randint(1,100,10).min()

1

In [173]:
np.random.randint(1,100,10).argmax()

3

In [174]:
np.random.randint(1,100,10).argmin()

0

In [175]:
np.arange(16).shape

(16,)

In [176]:
np.arange(16).size

16

In [177]:
np.arange(16).dtype

dtype('int64')