In [35]:
import numpy as np

In [36]:
my_list = [-1,0,1]
my_list, type(my_list)

([-1, 0, 1], list)

In [37]:
my_array = np.array(my_list)
my_array,type(my_array)


(array([-1,  0,  1]), numpy.ndarray)

In [38]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [39]:
ar1=np.array(my_matrix)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
my_tuple = (-1,0,1)
my_array = np.array(my_tuple)
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [41]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [43]:
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

In [44]:
np.arange(0,10,2, dtype=int)

array([0, 2, 4, 6, 8])

In [45]:
np.linspace(1,15,15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [46]:
np.linspace(5,15,9, retstep=True)

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [47]:
my_space=np.linspace(5,15,9, retstep=True)
my_space

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [48]:
np.zeros(3)

array([0., 0., 0.])

In [49]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.ones(3)

array([1., 1., 1.])

In [51]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.random.rand(3)

array([0.91927281, 0.44499786, 0.54000495])

In [54]:
np.random.rand(3,5)

array([[0.71152289, 0.77175396, 0.02501871, 0.15722701, 0.35717077],
       [0.61338195, 0.70132584, 0.45063236, 0.03218523, 0.87833348],
       [0.0651967 , 0.01049176, 0.73089182, 0.30244262, 0.26674072]])

In [55]:
np.random.randn(2)

array([-1.22463943,  0.37246289])

In [56]:
np.random.randn(4,4)

array([[ 1.49705849, -0.31515363,  0.32320589, -0.1982373 ],
       [-0.05833529, -0.68628601,  0.51343169,  2.12705162],
       [-0.13991185,  2.0829127 ,  0.1718516 ,  0.64487693],
       [ 0.54028512,  0.42149108,  0.43491193,  0.19617057]])

In [57]:
np.random.randint(1,100)

14

In [58]:
np.random.randint(1,100,10)

array([82, 54, 86, 28, 32,  7, 51, 88, 25, 61])

In [59]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [60]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.random.randint(1,100,10).max()

93

In [62]:
np.random.randint(1,100,10).min()

6

In [63]:
np.random.randint(1,100,10).argmax()

1

In [64]:
np.random.randint(1,100,10).argmin()

1

In [65]:
np.arange(16).shape

(16,)

In [66]:
np.arange(16).size

16

In [67]:
np.arange(16).dtype

dtype('int64')

In [68]:
a=np.array([1,2,3,4,2,3,4,2,1,4,6])
b=np.unique(a)
print(b)

[1 2 3 4 6]
